# This only exists so that we can include pedantic in the top level
# analysis_options.yaml. Each plugin should be published from its own
# subdirectory underneath packages/.
name: flutter_glove_box
dev_dependencies:
  pedantic: ^1.9.0
publish_to: none
