name: golden_toolkit
description: Common patterns for screenshot-based widget testing using Goldens.
version: 0.8.0
homepage: https://github.com/eBay/flutter_glove_box/
repository: https://github.com/eBay/flutter_glove_box/tree/master/packages/golden_toolkit
issue_tracker: https://github.com/eBay/flutter_glove_box/issues

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  sample_dependency:
    path: test/sample_dependency

flutter:
  uses-material-design: true
  assets:
    # needed to trigger the FontManifest.json to be included
    - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/golden_toolkit/fonts/Roboto-Regular.ttf
