name: golden_toolkit
description: Common patterns for screenshot-based widget testing using Goldens.
version: 0.2.1
homepage: https://github.com/eBay/flutter_glove_box/
repository: https://github.com/eBay/flutter_glove_box/tree/master/packages/golden_toolkit
issue_tracker: https://github.com/eBay/flutter_glove_box/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  sample_dependency:
    path: test/sample_dependency

# needed so the images can be loaded in the example tests
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/golden_toolkit/fonts/Roboto-Regular.ttf
