name: example
description: Demonstrate how golden toolkit can be used to
version: 0.0.1
author:

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit:
    path: ../
  pedantic: ^1.10.0-nullsafety.3

flutter:
  uses-material-design: true
  assets:
    - images/
